### ISSUE TITLE
Real-world Test Set

### ISSUE THREAD

**Issue by shangwei5** [zzh-tech/Dual-Reversed-RS#1]
Hi, Zhong, nice work for dual reversed distortion,

  Do you have any plans to release the Real-world Test Set? Thanks first.

**Comment by zzh-tech** [comment]
Thank you for your interest in our work!
The journal version of this paper is still being expanded, but you can try the two real-world examples (r0 and r1) that I put in the demo directory first.

**Comment by shangwei5** [comment]
> Thank you for your interest in our work! The journal version of this paper is still being expanded, but you can try the two real-world examples (r0 and r1) that I put in the demo directory first.

Thank you for the answer.
